//! Raw Gurobi C FFI bindings (auto-generated by bindgen).
//!
//! This file includes the bindgen-generated bindings from `gurobi_c.h`.
//! The bindings are generated at build time by `build.rs` and written to
//! `$OUT_DIR/gurobi_bindings.rs`.
//!
//! When `GUROBI_HOME` is not set, the bindings file is empty, allowing
//! the project to compile without Gurobi installed (but Gurobi functions
//! will not be available at runtime).

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/gurobi_bindings.rs"));
