//! Gurobi MIP solver integration via C FFI.
//!
//! This module provides a minimal safe Rust wrapper around the Gurobi C API,
//! sufficient for building and solving mixed-integer programs (MIP) needed
//! for scenario-based robust trajectory optimization.
//!
//! The raw C bindings are auto-generated by `bindgen` at build time from
//! `gurobi_c.h`. This wrapper exposes only the functions needed for MIP:
//! environment/model lifecycle, variable/constraint management, and solving.
//!
//! # Architecture (from star project)
//!
//! ```text
//! GrbModel::new()           — GRBemptyenv / GRBstartenv / GRBnewmodel
//! GrbModel::add_var()       — GRBaddvar
//! GrbModel::add_constr()    — GRBaddconstr
//! GrbModel::set_objective() — GRBsetdblattrelement (Obj attr)
//! GrbModel::optimize()      — GRBupdatemodel / GRBoptimize
//! GrbModel::get_solution()  — GRBgetdblattrarray (X attr)
//! ```
//!
//! # Feature Gate
//!
//! This module is only compiled when the `gurobi` feature is enabled (default).
//! When disabled, the module exists but contains no functional code.

pub mod ffi;
pub mod model;
